display_errors = Off
log_errors = On
error_log = /dev/stderr
upload_max_filesize = 32M
post_max_size = 40M
memory_limit = 256M
max_execution_time = 90
date.timezone = America/Sao_Paulo
expose_php = Off
